Fixes #2932: Move VT v5.12.1.2 changes into v1.5 branch
---svn-pre-commit-ignore-below---
r25595
Changes to VT:
	- Use own implementation of assert() to work around a compiler bug (seen on MacOS using GCC v4.2.1):
	  The linker results in an undefined reference to ___builtin_expect() when using assert() within OpenMP-parallel regions.

r25598
Changes to VT:
	- removed unnecessary trailing ';' from several macro definitions