Changes to VT: 	- Use own implementation of assert() to work around a compiler bug (seen on MacOS using GCC v4.2.1): 	  The linker results in an undefined reference to ___builtin_expect() when using assert() within OpenMP-parallel regions.